In [1]:
import pandas as pd
from datetime import datetime, date, time, timedelta

In [2]:
d1, d2 = date(2021, 5, 14), '2025-05-14'

print(d1)
print(d2)

2021-05-14
2025-05-14

In [3]:
print(type(d1))
print(type(d2))

<class 'datetime.date'>
<class 'str'>

In [4]:
date_today = date.today()
date_today

print(date_today.month)

3

In [5]:
t1 = time(13, 20, 13, 40)
t2 = '13:20:13.000040'
print(t1)
print(t2)
print(type(t1))
print(type(t2))

13:20:13.000040
13:20:13.000040
<class 'datetime.time'>
<class 'str'>

In [6]:
dt1 = datetime(2021, 5, 14, 11, 20, 30, 40)

# …and print it.
print(dt1)
print(type(dt1))

2021-05-14 11:20:30.000040
<class 'datetime.datetime'>

In [7]:
date_time = datetime.now()

print(date_time.isoweekday())
print('Date:', date_time.isocalendar())
print('Year:', date_time.isocalendar()[0])
print('Week:', date_time.isocalendar()[1])
print('Weekday:', date_time.isocalendar()[2])

5
Date: datetime.IsoCalendarDate(year=2026, week=11, weekday=5)
Year: 2026
Week: 11
Weekday: 5

In [8]:
d1 = date(2021, 5, 14)
d2 = '2025-05-14'

date_str = datetime.strptime(d2,'%Y-%m-%d').date()

print(d1)
print(d2)
print(date_str)


print(type(d1))
print(type(d2))
print(type(date_str))

2021-05-14
2025-05-14
2025-05-14
<class 'datetime.date'>
<class 'str'>
<class 'datetime.date'>

In [9]:
df = pd.read_csv("/Users/matthewhugo/Documents/2026_neuefische_DataEng/de-week-1-Python/05_pandas_intro/data/seattle-weather.csv")

In [10]:
df.head()

         date  precipitation  temp_max  temp_min  wind  weather
0  2012/01/01            0.0      12.8       5.0   4.7  drizzle
1  2012/01/02           10.9      10.6       2.8   4.5     rain
2  2012/01/03            0.8      11.7       7.2   2.3     rain
3  2012/01/04           20.3      12.2       5.6   4.7     rain
4  2012/01/05            1.3       8.9       2.8   6.1     rain

In [11]:
df.columns

Index(['date', 'precipitation', 'temp_max', 'temp_min', 'wind', 'weather'], dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   str
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: float64(4), str(2)
memory usage: 68.6 KB

In [13]:
df.shape

(1461, 6)

In [14]:
df.describe()

       precipitation     temp_max     temp_min         wind
count    1461.000000  1461.000000  1461.000000  1461.000000
mean        3.029432    16.439083     8.234771     3.241136
std         6.680194     7.349758     5.023004     1.437825
min         0.000000    -1.600000    -7.100000     0.400000
25%         0.000000    10.600000     4.400000     2.200000
50%         0.000000    15.600000     8.300000     3.000000
75%         2.800000    22.200000    12.200000     4.000000
max        55.900000    35.600000    18.300000     9.500000

In [15]:
pd.date_range(start='2025-03-14', end='14/04/2025', freq='W')

DatetimeIndex(['2025-03-16', '2025-03-23', '2025-03-30', '2025-04-06',
               '2025-04-13'],
              dtype='datetime64[us]', freq='W-SUN')

In [ ]:
from datetime import datetime

start_date = datetime.today().date()
start_example = pd.date_range(end=start_date, periods=10, freq='D')

for x in start_example:
    print(x.strftime('%Y-%m-%d'))

2026-03-04
2026-03-05
2026-03-06
2026-03-07
2026-03-08
2026-03-09
2026-03-10
2026-03-11
2026-03-12
2026-03-13

In [9]:
import pandas as pd
from datetime import datetime, date, time, timedelta

start_date = datetime.today()
date_start = pd.date_range(start=start_date, periods=10, freq='D')
date_end = pd.date_range(start=start_date, periods=10, freq='D')

df = pd.DataFrame()
df['Start_day'] = date_start
df['End_day'] = date_end
df['Date_diff_days'] = date_end - date_start
df['Day_of_end_date'] = df['End_day'].dt.day
df['Month_of_start_date'] = df['Start_day'].dt.month_name()
df['Year_of_start_date'] = df['Start_day'].dt.year

df.head()

,Start_day,End_day,Date_diff_days,Day_of_end_date,Month_of_start_date,Year_of_start_date
0,2026-03-13 17:46:33.816309,2026-03-13 17:46:33.816309,0 days,13,March,2026
1,2026-03-14 17:46:33.816309,2026-03-14 17:46:33.816309,0 days,14,March,2026
2,2026-03-15 17:46:33.816309,2026-03-15 17:46:33.816309,0 days,15,March,2026
3,2026-03-16 17:46:33.816309,2026-03-16 17:46:33.816309,0 days,16,March,2026
4,2026-03-17 17:46:33.816309,2026-03-17 17:46:33.816309,0 days,17,March,2026

In [11]:
df = pd.read_csv("/Users/matthewhugo/Documents/2026_neuefische_DataEng/de-week-1-Python/05_pandas_intro/data/seattle-weather.csv")

In [12]:
df.head()

         date  precipitation  temp_max  temp_min  wind  weather
0  2012/01/01            0.0      12.8       5.0   4.7  drizzle
1  2012/01/02           10.9      10.6       2.8   4.5     rain
2  2012/01/03            0.8      11.7       7.2   2.3     rain
3  2012/01/04           20.3      12.2       5.6   4.7     rain
4  2012/01/05            1.3       8.9       2.8   6.1     rain

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[us]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   str
dtypes: datetime64[us](1), float64(4), str(1)
memory usage: 68.6 KB

In [14]:
df.date = pd.to_datetime(df.date, format='%Y/%m/%d')